"""
executor.py

Security Test Execution Engine for API Sentinel AI.

This module is responsible for executing the security
tests generated by the LLM Test Planner.

Responsibilities
----------------
1. Build HTTP requests.
2. Execute security payloads.
3. Capture HTTP responses.
4. Store execution results.
5. Provide structured output for validation.

The executor never determines WHAT to test.
It only executes the supplied TestPlan.
"""

from __future__ import annotations

import logging
import time
import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import requests

from scanner.planner import TestCase, TestPlan

logger = logging.getLogger(__name__)


# ---------------------------------------------------------
# Configuration
# ---------------------------------------------------------

DEFAULT_TIMEOUT = 15

DEFAULT_USER_AGENT = "API-Sentinel-AI/1.0"


# ---------------------------------------------------------
# Data Models
# ---------------------------------------------------------

@dataclass
class ExecutionResult:
    """
    Result of one executed security test.
    """

    test_case: TestCase

    success: bool

    status_code: int

    response_time_ms: float

    response_headers: Dict[str, Any]

    response_body: str

    error_message: Optional[str] = None


@dataclass
class ExecutionReport:
    """
    Collection of execution results for an endpoint.
    """

    plan: TestPlan

    executed_at: float

    results: List[ExecutionResult] = field(default_factory=list)


# ---------------------------------------------------------
# Exceptions
# ---------------------------------------------------------

class ExecutorError(Exception):
    """Base executor exception."""


class RequestExecutionError(ExecutorError):
    """Raised when an HTTP request cannot be executed."""


# ---------------------------------------------------------
# Security Test Executor
# ---------------------------------------------------------

class SecurityTestExecutor:
    """
    Executes security tests generated by
    the LLM Test Planner.
    """

    def __init__(
        self,
        timeout: int = DEFAULT_TIMEOUT,
    ) -> None:

        self.timeout = timeout

        self.session = requests.Session()

        self.session.headers.update(
            {
                "User-Agent": DEFAULT_USER_AGENT,
            }
        )

        logger.info(
            "Security Test Executor initialized."
        )

    # -----------------------------------------------------
    # Public API
    # -----------------------------------------------------

    def execute_plan(
        self,
        base_url: str,
        plan: TestPlan,
    ) -> ExecutionReport:
        """
        Execute every test case in a TestPlan.
        """

        logger.info(
            "Executing %d test cases.",
            len(plan.test_cases),
        )

        report = ExecutionReport(
            plan=plan,
            executed_at=time.time(),
        )

        for test_case in plan.test_cases:

            result = self._execute_test_case(
                base_url,
                plan,
                test_case,
            )

            report.results.append(result)

        return report

    # -----------------------------------------------------
    # Internal Methods
    # -----------------------------------------------------

    def _execute_test_case(
        self,
        base_url: str,
        plan: TestPlan,
        test_case: TestCase,
    ) -> ExecutionResult:
        raise NotImplementedError

    def _build_request(
        self,
        base_url: str,
        plan: TestPlan,
        test_case: TestCase,
    ) -> Dict[str, Any]:
        raise NotImplementedError

    def _send_request(
        self,
        request_data: Dict[str, Any],
    ) -> requests.Response:
        raise NotImplementedError
    # ---------------------------------------------------------
    # Request Builder
    # ---------------------------------------------------------

    def _build_request(
        self,
        base_url: str,
        plan: TestPlan,
        test_case: TestCase,
    ) -> Dict[str, Any]:
        """
        Build a complete HTTP request for a security test.
        """

        endpoint = plan.endpoint.endpoint

        url = (
            base_url.rstrip("/")
            + endpoint.path
        )

        headers = self._build_headers()

        params = self._build_query_parameters(endpoint)

        json_body = self._build_request_body(
            endpoint,
            test_case,
        )

        return {
            "method": endpoint.method.upper(),
            "url": url,
            "headers": headers,
            "params": params,
            "json": json_body,
        }

    # ---------------------------------------------------------
    # Headers
    # ---------------------------------------------------------

    def _build_headers(
        self,
    ) -> Dict[str, str]:
        """
        Construct default request headers.
        """

        return {
            "User-Agent": DEFAULT_USER_AGENT,
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

    # ---------------------------------------------------------
    # Query Parameters
    # ---------------------------------------------------------

    def _build_query_parameters(
        self,
        endpoint,
    ) -> Dict[str, Any]:
        """
        Build query parameters using placeholder values.
        """

        parameters = {}

        for parameter in endpoint.parameters:

            if parameter.get("in") != "query":
                continue

            parameters[
                parameter.get("name")
            ] = self._placeholder_value(
                parameter
            )

        return parameters

    # ---------------------------------------------------------
    # Request Body
    # ---------------------------------------------------------

    def _build_request_body(
        self,
        endpoint,
        test_case: TestCase,
    ) -> Dict[str, Any]:
        """
        Construct a request body from the endpoint schema.
        """

        body = {}

        schema = endpoint.request_body

        if not schema:
            return body

        properties = schema.get(
            "properties",
            {},
        )

        for field, details in properties.items():

            body[field] = self._placeholder_value(
                details
            )

        payload = self._payload_for_test(
            test_case
        )

        if payload:

            body.update(payload)

        return body

    # ---------------------------------------------------------
    # Placeholder Generator
    # ---------------------------------------------------------

    def _placeholder_value(
        self,
        schema: Dict[str, Any],
    ) -> Any:
        """
        Generate placeholder values based on schema type.
        """

        value_type = schema.get(
            "type",
            "string",
        )

        placeholders = {
            "string": "sample",
            "integer": 1,
            "number": 1.0,
            "boolean": True,
            "array": [],
            "object": {},
        }

        return placeholders.get(
            value_type,
            "sample",
        )

    # ---------------------------------------------------------
    # Payload Selection
    # ---------------------------------------------------------

    def _payload_for_test(
        self,
        test_case: TestCase,
    ) -> Dict[str, Any]:
        """
        Select a payload based on the OWASP category.
        """

        payloads = {
            "API1": {
                "id": -1,
            },
            "API2": {
                "password": "' OR '1'='1",
            },
            "API3": {
                "role": "admin",
            },
            "API4": {
                "limit": 100000,
            },
            "API5": {
                "admin": True,
            },
            "API6": {
                "amount": 99999999,
            },
            "API7": {
                "url": "http://127.0.0.1",
            },
            "API8": {},
            "API9": {},
            "API10": {
                "callback": "http://malicious.example",
            },
        }

        return payloads.get(
            test_case.owasp_category,
            {},
        )
    # ---------------------------------------------------------
    # Execute Single Test
    # ---------------------------------------------------------

    def _execute_test_case(
        self,
        base_url: str,
        plan: TestPlan,
        test_case: TestCase,
    ) -> ExecutionResult:
        """
        Execute a single security test case.
        """

        request_data = self._build_request(
            base_url,
            plan,
            test_case,
        )

        start_time = time.perf_counter()

        try:

            response = self._send_request(
                request_data
            )

            elapsed = (
                time.perf_counter() - start_time
            ) * 1000

            logger.info(
                "Executed %s (%s)",
                test_case.title,
                response.status_code,
            )

            return ExecutionResult(
                test_case=test_case,
                success=True,
                status_code=response.status_code,
                response_time_ms=round(
                    elapsed,
                    2,
                ),
                response_headers=dict(
                    response.headers
                ),
                response_body=response.text,
            )

        except RequestExecutionError as exc:

            logger.exception(
                "Execution failed."
            )

            return ExecutionResult(
                test_case=test_case,
                success=False,
                status_code=0,
                response_time_ms=0,
                response_headers={},
                response_body="",
                error_message=str(exc),
            )

    # ---------------------------------------------------------
    # HTTP Sender
    # ---------------------------------------------------------

    def _send_request(
        self,
        request_data: Dict[str, Any],
    ) -> requests.Response:
        """
        Execute an HTTP request.
        """

        try:

            response = self.session.request(
                method=request_data["method"],
                url=request_data["url"],
                headers=request_data["headers"],
                params=request_data["params"],
                json=request_data["json"],
                timeout=self.timeout,
            )

            return response

        except requests.RequestException as exc:

            raise RequestExecutionError(
                str(exc)
            ) from exc
    # ---------------------------------------------------------
    # Response Analysis
    # ---------------------------------------------------------

    def analyze_response(
        self,
        result: ExecutionResult,
    ) -> Dict[str, Any]:
        """
        Extract useful metadata from an execution result.
        This does not determine vulnerabilities; it only
        collects evidence for later validation.
        """

        headers = result.response_headers

        analysis = {
            "status_code": result.status_code,
            "response_time_ms": result.response_time_ms,
            "response_size": len(result.response_body),
            "content_type": headers.get(
                "Content-Type",
                "Unknown",
            ),
            "server": headers.get(
                "Server",
                "Unknown",
            ),
            "security_headers": self._check_security_headers(
                headers
            ),
        }

        return analysis

    # ---------------------------------------------------------
    # Security Header Inspection
    # ---------------------------------------------------------

    def _check_security_headers(
        self,
        headers: Dict[str, Any],
    ) -> Dict[str, bool]:
        """
        Check for commonly recommended security headers.
        """

        required_headers = [
            "X-Content-Type-Options",
            "X-Frame-Options",
            "Content-Security-Policy",
            "Strict-Transport-Security",
            "Referrer-Policy",
        ]

        return {
            header: header in headers
            for header in required_headers
        }

    # ---------------------------------------------------------
    # Execution Summary
    # ---------------------------------------------------------

    def summarize_execution(
        self,
        report: ExecutionReport,
    ) -> Dict[str, Any]:
        """
        Generate summary statistics for an execution report.
        """

        total = len(report.results)

        successful = sum(
            1
            for result in report.results
            if result.success
        )

        failed = total - successful

        average_time = (
            sum(
                result.response_time_ms
                for result in report.results
            )
            / total
            if total
            else 0
        )

        return {
            "endpoint": (
                f"{report.plan.endpoint.endpoint.method} "
                f"{report.plan.endpoint.endpoint.path}"
            ),
            "total_tests": total,
            "successful_tests": successful,
            "failed_tests": failed,
            "average_response_time_ms": round(
                average_time,
                2,
            ),
        }
    # ---------------------------------------------------------
    # Serialization
    # ---------------------------------------------------------

    def result_to_dict(
        self,
        result: ExecutionResult,
    ) -> Dict[str, Any]:
        """
        Convert an ExecutionResult into a JSON-serializable dictionary.
        """

        return {
            "test_title": result.test_case.title,
            "owasp_category": result.test_case.owasp_category,
            "priority": result.test_case.priority,
            "success": result.success,
            "status_code": result.status_code,
            "response_time_ms": result.response_time_ms,
            "response_headers": result.response_headers,
            "response_body": result.response_body,
            "error_message": result.error_message,
        }

    def report_to_dict(
        self,
        report: ExecutionReport,
    ) -> Dict[str, Any]:
        """
        Convert an ExecutionReport into a JSON-serializable dictionary.
        """

        return {
            "endpoint": {
                "method": report.plan.endpoint.endpoint.method,
                "path": report.plan.endpoint.endpoint.path,
            },
            "executed_at": report.executed_at,
            "summary": self.summarize_execution(report),
            "results": [
                self.result_to_dict(result)
                for result in report.results
            ],
        }

    # ---------------------------------------------------------
    # Export
    # ---------------------------------------------------------

    def export_report(
        self,
        report: ExecutionReport,
        output_file: str,
    ) -> None:
        """
        Export a single execution report.
        """

        logger.info(
            "Exporting execution report to %s",
            output_file,
        )

        with open(
            output_file,
            "w",
            encoding="utf-8",
        ) as file:

            json.dump(
                self.report_to_dict(report),
                file,
                indent=4,
            )

    def export_reports(
        self,
        reports: List[ExecutionReport],
        output_file: str,
    ) -> None:
        """
        Export multiple execution reports.
        """

        logger.info(
            "Exporting %d execution reports",
            len(reports),
        )

        with open(
            output_file,
            "w",
            encoding="utf-8",
        ) as file:

            json.dump(
                [
                    self.report_to_dict(report)
                    for report in reports
                ],
                file,
                indent=4,
            )

    # ---------------------------------------------------------
    # Batch Execution
    # ---------------------------------------------------------

    def execute_plans(
        self,
        base_url: str,
        plans: List[TestPlan],
    ) -> List[ExecutionReport]:
        """
        Execute multiple test plans.
        """

        reports: List[ExecutionReport] = []

        logger.info(
            "Executing %d test plans.",
            len(plans),
        )

        for plan in plans:

            reports.append(
                self.execute_plan(
                    base_url,
                    plan,
                )
            )

        logger.info(
            "Execution complete."
        )

        return reports

    # ---------------------------------------------------------
    # Cleanup
    # ---------------------------------------------------------

    def close(self) -> None:
        """
        Close the underlying HTTP session.
        """

        self.session.close()

        logger.info(
            "HTTP session closed."
        )