"""
validator.py

Validation Engine for API Sentinel AI.

This module analyzes the execution results produced
by the Security Test Executor and determines whether
they represent genuine security findings.

Responsibilities
----------------
1. Validate execution results.
2. Detect likely vulnerabilities.
3. Collect supporting evidence.
4. Produce structured validation reports.

This module does NOT assign business risk.
Risk scoring is handled by the Risk Engine.
"""

from __future__ import annotations

import logging
import time
import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from scanner.executor import (
    ExecutionReport,
    ExecutionResult,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------
# Data Models
# ---------------------------------------------------------

@dataclass
class ValidationFinding:
    """
    Represents one validated security finding.
    """

    title: str

    owasp_category: str

    severity: str

    confidence: float

    description: str

    evidence: Dict[str, Any]

    recommendation: str


@dataclass
class ValidationResult:
    """
    Validation result for one executed test.
    """

    execution: ExecutionResult

    passed: bool

    findings: List[ValidationFinding] = field(
        default_factory=list
    )


@dataclass
class ValidationReport:
    """
    Validation report for an endpoint.
    """

    execution_report: ExecutionReport

    validated_at: float

    results: List[ValidationResult] = field(
        default_factory=list
    )


# ---------------------------------------------------------
# Exceptions
# ---------------------------------------------------------

class ValidationError(Exception):
    """Base validation exception."""


# ---------------------------------------------------------
# Validation Engine
# ---------------------------------------------------------

class ValidationEngine:
    """
    Validate execution reports generated by
    the Security Test Executor.
    """

    def validate_report(
        self,
        report: ExecutionReport,
    ) -> ValidationReport:
        """
        Validate every execution result.
        """

        logger.info(
            "Validating %d execution results.",
            len(report.results),
        )

        validation = ValidationReport(
            execution_report=report,
            validated_at=time.time(),
        )

        for result in report.results:

            validation.results.append(
                self._validate_result(result)
            )

        return validation

    # -----------------------------------------------------
    # Internal Validators
    # -----------------------------------------------------

    def _validate_result(
        self,
        result: ExecutionResult,
    ) -> ValidationResult:
        raise NotImplementedError

    def _collect_findings(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:
        raise NotImplementedError
    # ---------------------------------------------------------
    # Validate Single Result
    # ---------------------------------------------------------

    def _validate_result(
        self,
        result: ExecutionResult,
    ) -> ValidationResult:
        """
        Validate one execution result.
        """

        findings = self._collect_findings(result)

        return ValidationResult(
            execution=result,
            passed=len(findings) == 0,
            findings=findings,
        )

    # ---------------------------------------------------------
    # Finding Collection
    # ---------------------------------------------------------

    def _collect_findings(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:
        """
        Execute all validation checks and collect findings.
        """

        findings: List[ValidationFinding] = []

        findings.extend(
            self._validate_status_code(result)
        )

        findings.extend(
            self._validate_security_headers(result)
        )

        findings.extend(
            self._validate_response_body(result)
        )

        return findings

    # ---------------------------------------------------------
    # Status Code Validation
    # ---------------------------------------------------------

    def _validate_status_code(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:
        """
        Identify suspicious HTTP status codes.
        """

        findings = []

        if result.status_code >= 500:

            findings.append(
                ValidationFinding(
                    title="Server Error Detected",
                    owasp_category="General",
                    severity="MEDIUM",
                    confidence=0.80,
                    description=(
                        "The API returned a server-side error "
                        "during security testing."
                    ),
                    evidence={
                        "status_code": result.status_code,
                    },
                    recommendation=(
                        "Review server logs and exception handling."
                    ),
                )
            )

        return findings

    # ---------------------------------------------------------
    # Security Header Validation
    # ---------------------------------------------------------

    def _validate_security_headers(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:
        """
        Check for missing recommended security headers.
        """

        findings = []

        required_headers = [
            "X-Content-Type-Options",
            "X-Frame-Options",
            "Content-Security-Policy",
            "Strict-Transport-Security",
        ]

        missing = [
            header
            for header in required_headers
            if header not in result.response_headers
        ]

        if missing:

            findings.append(
                ValidationFinding(
                    title="Missing Security Headers",
                    owasp_category="API8",
                    severity="LOW",
                    confidence=0.90,
                    description=(
                        "The response is missing one or more "
                        "recommended security headers."
                    ),
                    evidence={
                        "missing_headers": missing,
                    },
                    recommendation=(
                        "Configure the web server to include the "
                        "recommended security headers."
                    ),
                )
            )

        return findings

    # ---------------------------------------------------------
    # Response Body Validation
    # ---------------------------------------------------------

    def _validate_response_body(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:
        """
        Inspect the response body for common indicators
        of information leakage.
        """

        findings = []

        body = result.response_body.lower()

        suspicious_patterns = [
            "traceback",
            "exception",
            "stack trace",
            "sql syntax",
            "internal server error",
            "nullpointerexception",
            "fatal error",
        ]

        matches = [
            pattern
            for pattern in suspicious_patterns
            if pattern in body
        ]

        if matches:

            findings.append(
                ValidationFinding(
                    title="Sensitive Error Information Exposed",
                    owasp_category="API8",
                    severity="MEDIUM",
                    confidence=0.95,
                    description=(
                        "The API response appears to expose "
                        "internal implementation details."
                    ),
                    evidence={
                        "matched_patterns": matches,
                    },
                    recommendation=(
                        "Replace detailed exception messages with "
                        "generic error responses."
                    ),
                )
            )

        return findings
    # ---------------------------------------------------------
    # OWASP API Validation
    # ---------------------------------------------------------

    def _validate_result(
        self,
        result: ExecutionResult,
    ) -> ValidationResult:
        """
        Validate one execution result.
        """

        findings = self._collect_findings(result)

        findings.extend(
            self._validate_owasp(result)
        )

        return ValidationResult(
            execution=result,
            passed=len(findings) == 0,
            findings=findings,
        )

    def _validate_owasp(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:
        """
        Dispatch validation based on the OWASP category.
        """

        category = result.test_case.owasp_category

        validators = {
            "API1": self._validate_api1,
            "API2": self._validate_api2,
            "API3": self._validate_api3,
            "API4": self._validate_api4,
            "API5": self._validate_api5,
            "API6": self._validate_api6,
            "API7": self._validate_api7,
            "API8": self._validate_api8,
            "API9": self._validate_api9,
            "API10": self._validate_api10,
        }

        validator = validators.get(category)

        if validator:

            return validator(result)

        return []

    # ---------------------------------------------------------
    # API1 - Broken Object Level Authorization
    # ---------------------------------------------------------

    def _validate_api1(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:

        if result.status_code == 200:

            return [
                ValidationFinding(
                    title="Possible Broken Object Level Authorization",
                    owasp_category="API1",
                    severity="HIGH",
                    confidence=0.85,
                    description=(
                        "The endpoint returned a successful response "
                        "to an authorization test."
                    ),
                    evidence={
                        "status_code": result.status_code,
                    },
                    recommendation=(
                        "Verify authorization checks before returning "
                        "object data."
                    ),
                )
            ]

        return []

    # ---------------------------------------------------------
    # API2 - Broken Authentication
    # ---------------------------------------------------------

    def _validate_api2(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:

        body = result.response_body.lower()

        if (
            result.status_code == 200
            and "token" in body
        ):

            return [
                ValidationFinding(
                    title="Possible Authentication Bypass",
                    owasp_category="API2",
                    severity="CRITICAL",
                    confidence=0.92,
                    description=(
                        "Authentication test appears to have "
                        "returned valid credentials."
                    ),
                    evidence={
                        "status_code": result.status_code,
                    },
                    recommendation=(
                        "Review authentication and credential "
                        "validation logic."
                    ),
                )
            ]

        return []

    # ---------------------------------------------------------
    # API3 - Broken Object Property Level Authorization
    # ---------------------------------------------------------

    def _validate_api3(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:

        if result.status_code == 200:

            return [
                ValidationFinding(
                    title="Possible Mass Assignment",
                    owasp_category="API3",
                    severity="HIGH",
                    confidence=0.80,
                    description=(
                        "Sensitive properties may be writable."
                    ),
                    evidence={
                        "status_code": result.status_code,
                    },
                    recommendation=(
                        "Restrict writable object properties."
                    ),
                )
            ]

        return []

    # ---------------------------------------------------------
    # API4 - Unrestricted Resource Consumption
    # ---------------------------------------------------------

    def _validate_api4(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:

        if result.response_time_ms > 5000:

            return [
                ValidationFinding(
                    title="Possible Resource Exhaustion",
                    owasp_category="API4",
                    severity="MEDIUM",
                    confidence=0.82,
                    description=(
                        "Large payload caused unusually slow response."
                    ),
                    evidence={
                        "response_time_ms": result.response_time_ms,
                    },
                    recommendation=(
                        "Implement request limits and throttling."
                    ),
                )
            ]

        return []

    # ---------------------------------------------------------
    # Remaining Categories
    # ---------------------------------------------------------

    def _validate_api5(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:
        return []

    def _validate_api6(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:
        return []

    def _validate_api7(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:
        return []

    def _validate_api8(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:
        return []

    def _validate_api9(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:
        return []

    def _validate_api10(
        self,
        result: ExecutionResult,
    ) -> List[ValidationFinding]:
        return []
    # ---------------------------------------------------------
    # Confidence Calculation
    # ---------------------------------------------------------

    def calculate_confidence(
        self,
        finding: ValidationFinding,
    ) -> float:
        """
        Adjust confidence based on the available evidence.
        """

        confidence = finding.confidence

        evidence = finding.evidence

        if "status_code" in evidence:
            confidence += 0.03

        if "matched_patterns" in evidence:
            confidence += 0.05

        if "missing_headers" in evidence:
            confidence += 0.02

        if "response_time_ms" in evidence:
            confidence += 0.02

        return min(confidence, 1.0)

    # ---------------------------------------------------------
    # Normalize Findings
    # ---------------------------------------------------------

    def normalize_findings(
        self,
        findings: List[ValidationFinding],
    ) -> List[ValidationFinding]:
        """
        Update confidence values before reporting.
        """

        normalized = []

        for finding in findings:

            finding.confidence = self.calculate_confidence(
                finding
            )

            normalized.append(finding)

        return normalized

    # ---------------------------------------------------------
    # Remove Duplicate Findings
    # ---------------------------------------------------------

    def deduplicate_findings(
        self,
        findings: List[ValidationFinding],
    ) -> List[ValidationFinding]:
        """
        Remove duplicate findings while preserving order.
        """

        unique = []
        seen = set()

        for finding in findings:

            key = (
                finding.title,
                finding.owasp_category,
            )

            if key in seen:
                continue

            seen.add(key)

            unique.append(finding)

        return unique

    # ---------------------------------------------------------
    # Validation Statistics
    # ---------------------------------------------------------

    def validation_statistics(
        self,
        report: ValidationReport,
    ) -> Dict[str, Any]:
        """
        Generate validation statistics.
        """

        total_results = len(report.results)

        total_findings = sum(
            len(result.findings)
            for result in report.results
        )

        passed = sum(
            1
            for result in report.results
            if result.passed
        )

        failed = total_results - passed

        by_severity = {
            "CRITICAL": 0,
            "HIGH": 0,
            "MEDIUM": 0,
            "LOW": 0,
        }

        for result in report.results:

            for finding in result.findings:

                severity = finding.severity.upper()

                if severity in by_severity:
                    by_severity[severity] += 1

        return {
            "validated_tests": total_results,
            "passed": passed,
            "failed": failed,
            "findings": total_findings,
            "severity": by_severity,
        }

    # ---------------------------------------------------------
    # Finalize Report
    # ---------------------------------------------------------

    def finalize_report(
        self,
        report: ValidationReport,
    ) -> ValidationReport:
        """
        Normalize and deduplicate findings before
        the report is passed to the Risk Engine.
        """

        for result in report.results:

            result.findings = self.normalize_findings(
                result.findings
            )

            result.findings = self.deduplicate_findings(
                result.findings
            )

        return report
    # ---------------------------------------------------------
    # Serialization
    # ---------------------------------------------------------

    def finding_to_dict(
        self,
        finding: ValidationFinding,
    ) -> Dict[str, Any]:
        """
        Convert a ValidationFinding into a JSON-serializable dictionary.
        """

        return {
            "title": finding.title,
            "owasp_category": finding.owasp_category,
            "severity": finding.severity,
            "confidence": finding.confidence,
            "description": finding.description,
            "evidence": finding.evidence,
            "recommendation": finding.recommendation,
        }

    def result_to_dict(
        self,
        result: ValidationResult,
    ) -> Dict[str, Any]:
        """
        Convert a ValidationResult into a dictionary.
        """

        return {
            "test_title": result.execution.test_case.title,
            "passed": result.passed,
            "findings": [
                self.finding_to_dict(finding)
                for finding in result.findings
            ],
        }

    def report_to_dict(
        self,
        report: ValidationReport,
    ) -> Dict[str, Any]:
        """
        Convert a ValidationReport into a dictionary.
        """

        endpoint = report.execution_report.plan.endpoint.endpoint

        return {
            "endpoint": {
                "method": endpoint.method,
                "path": endpoint.path,
            },
            "validated_at": report.validated_at,
            "statistics": self.validation_statistics(report),
            "results": [
                self.result_to_dict(result)
                for result in report.results
            ],
        }

    # ---------------------------------------------------------
    # Export
    # ---------------------------------------------------------

    def export_report(
        self,
        report: ValidationReport,
        output_file: str,
    ) -> None:
        """
        Export a validation report to JSON.
        """

        logger.info(
            "Exporting validation report to %s",
            output_file,
        )

        with open(
            output_file,
            "w",
            encoding="utf-8",
        ) as file:

            json.dump(
                self.report_to_dict(report),
                file,
                indent=4,
            )

    def export_reports(
        self,
        reports: List[ValidationReport],
        output_file: str,
    ) -> None:
        """
        Export multiple validation reports.
        """

        logger.info(
            "Exporting %d validation reports.",
            len(reports),
        )

        exported = [
            self.report_to_dict(report)
            for report in reports
        ]

        with open(
            output_file,
            "w",
            encoding="utf-8",
        ) as file:

            json.dump(
                exported,
                file,
                indent=4,
            )

    # ---------------------------------------------------------
    # Batch Validation
    # ---------------------------------------------------------

    def validate_reports(
        self,
        reports: List[ExecutionReport],
    ) -> List[ValidationReport]:
        """
        Validate multiple execution reports.
        """

        validation_reports: List[ValidationReport] = []

        logger.info(
            "Validating %d execution reports.",
            len(reports),
        )

        for report in reports:

            validated = self.validate_report(report)

            validated = self.finalize_report(
                validated
            )

            validation_reports.append(
                validated
            )

        logger.info(
            "Validation completed."
        )

        return validation_reports

    # ---------------------------------------------------------
    # Summary
    # ---------------------------------------------------------

    def generate_summary(
        self,
        report: ValidationReport,
    ) -> Dict[str, Any]:
        """
        Generate a concise summary of a validation report.
        """

        stats = self.validation_statistics(
            report
        )

        endpoint = report.execution_report.plan.endpoint.endpoint

        return {
            "endpoint": (
                f"{endpoint.method} {endpoint.path}"
            ),
            "validated_tests": stats["validated_tests"],
            "findings": stats["findings"],
            "passed": stats["passed"],
            "failed": stats["failed"],
            "severity_breakdown": stats["severity"],
        }